# docker-compose.yml
version: '3.8'
services:
    ui:
      build:
        context: .
        dockerfile: Dockerfile.react
      restart: on-failure
      # below line starts the project
      command: "npm start"
      networks:
        - pedro
      volumes:
        # this will mount the ui folder which contains the code to the docker container
        - ./:/usr/src/app:delegated
        # this will mount the node_modules folder for faster performance
        - nodemodules:/usr/src/app/node_modules
      ports:
        - "40420:3000"
      environment:
        - CHOKIDAR_USEPOLLING=true

volumes:
  nodemodules: {}

networks:
  pedro:
     name: pedro
     driver: bridge
     ipam:
      config:
        - subnet: 10.0.9.0/24
